server:
  port: 18084
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  sleuth:
    sampler:
      probability: 1
  zipkin:
    locator:
      discovery:
        enabled: false
    base-url: http://localhost:9411
    sender:
      type: web
  redis:
    host: 111.1.1.11
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.1.1.11:3306/guli_oms
    username: root
    password: 123456

feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/oms/**/*.xml
  type-aliases-package: com.atguigu.gmall.oms.entity
