
#端口号
server:
  port: 18088
#cloud
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    locator:
      discovery:
        enabled: false
  thymeleaf:
    cache: false
  redis:
    host: 111.1.1.11
    port: 6379
feign:
  sentinel:
    enabled: true
logging:
  level:
    com.atguigu.gmall.item.feign: debug
    com.alibaba.nacos.client.naming: warn
threadPool:
  coreSize: 100
  maxSize: 500
  keepAlive: 60
  blockingQueue: 1000
