
#端口号
server:
  port: 18086

  #cloud
spring:
  jackson:
    time-zone: GMT+8
    date-format: yy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    locator:
      discovery:
        enabled: false
  elasticsearch:
    rest:
      uris: http://111.1.1.11:9200
  thymeleaf:
    cache: false
  rabbitmq:
    host: 111.1.1.11
    port: 5672
    username: admin
    password: admin
    virtual-host: FAST_B15A
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        concurrency: 4
feign:
  sentinel:
    enabled: true
logging:
  level:
   com.atguigu.gmall.search.feign: debug
   com.alibaba.nacos.client.naming.updater: warn
