
#端口号
server:
  port: 18081

  #cloud
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
    alibaba:
      seata:
        tx-service-group: gmall-tx-group
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    locator:
      discovery:
        enabled: false

   #feign
  datasource:
    url: jdbc:mysql://111.1.1.11:3306/guli_pms
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: 111.1.1.11
    port: 6379
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/pms/**/*.xml
  type-aliases-package: com.atguigu.gmall.pms.entity
  global-config:
    db-config:
      id-type: auto
logging:
  level:
   com.atguigu.gmall.pms.mapper: debug
   com.atguigu.gmall.pms.feign: debug
   com.alibaba.nacos.client.naming.updater: warn
