
#端口号
server:
  port: 19999
#cloud
spring:
  rabbitmq:
    host: 111.1.1.11
    port: 5672
    username: admin
    password: admin
    virtual-host: FAST_B15A
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        concurrency: 4
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  redis:
    host: 111.1.1.11
    port: 6379
logging:
  level:
    com.atguigu.gmall.msg.feign: debug
    com.alibaba.nacos.client.naming: warn
code:
  key: 3
